-- Create plant_health_logs table
CREATE TABLE public.plant_health_logs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    plant_id TEXT,
    bio_signal REAL,
    soil_moisture INTEGER,
    temperature REAL,
    humidity REAL,
    vibration INTEGER,
    stress_type TEXT,
    CONSTRAINT plant_health_logs_pkey PRIMARY KEY (id)
);

-- Enable Row Level Security
ALTER TABLE public.plant_health_logs ENABLE ROW LEVEL SECURITY;

-- Create policy for public read access (dashboard is public)
CREATE POLICY "Anyone can read plant health logs"
ON public.plant_health_logs
FOR SELECT
USING (true);

-- Create policy for insert (for sensors/devices)
CREATE POLICY "Anyone can insert plant health logs"
ON public.plant_health_logs
FOR INSERT
WITH CHECK (true);

-- Enable realtime for this table
ALTER PUBLICATION supabase_realtime ADD TABLE public.plant_health_logs;